name: Test Tunnel

on: push

jobs:
  test-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      
      - name: Start LambdaTest Tunnel
        id: tunnel
        uses: ./ # Uses an action in the root directory
        with:
          user: ${{ secrets.LT_EMAIL }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "testTunnel"

      - run: echo 'Tunnel is running now'
      - run: curl http://127.0.0.1:${{ steps.tunnel.outputs.port }}/api/v1.0/info
      - run: sleep 45
      - run: echo 'We are done'
